### ISSUE TITLE
Ray computation from orientation

### ISSUE THREAD

**Issue by adakite** [rgerum/cameratransform#11]
Hi,

I might be wrong but I suspect a bug in the Ray computation from a camera orientation. It seems to me that the roll angle is not accounted for as when changing it does not affect the ray vector. 

```
cc = ct.Camera(ct.RectilinearProjection(focallength_px=3000, image=(2000, 2000)),
                          ct.SpatialOrientation(elevation_m=10, tilt_deg=12,roll_deg=0,heading_deg=0))
offset, ray = cc.getRay([1000, 1000],normed=False)
```
Returns
> array([ 0.        ,  0.20791169, -0.9781476 ])

and this:
```
cc = ct.Camera(ct.RectilinearProjection(focallength_px=3000, image=(2000, 2000)),
                          ct.SpatialOrientation(elevation_m=10, tilt_deg=12,roll_deg=20,heading_deg=0))
offset, ray = cc.getRay([1000, 1000],normed=False)
```
gives

> array([-1.47684333e-17,  2.07911691e-01, -9.78147601e-01])

So besides the numerical precision, this is the same ray while the roll angle changed from 0 to 20 degrees. We should have a y component much bigger than previously (and respectively a smaller z component). 

Did I miss something or is this a bug somewhere?

Thanks

**Comment by rgerum** [comment]
You are using directly the ray in the center of the image. Roll rotates around the center of the image and therefore does not affect the central ray. If you try a different ray, it will be affected by the roll.

**Comment by adakite** [comment]
Yes this is correct if the ray are expressed in the image frame, but the way I call it is through the RectilinearProjection and as stated in the doc (and is the source code) the ray should be expressed in the terrain frame, hence the roll should affect the ray for the boresight as well.

**Comment by rgerum** [comment]
Ok, maybe there is some confusion from the documentation. What a "ray" means in this context is a line (represented in world coordinates) that goes through the origin of the camera and through the pixel that is provided.
Or in other words, if you say cc.getRay([1000, 1000],normed=False) you get the line that represents the ray of light that falls onto the given pixel.
As you queried the central pixel of the image, the ray of light that falls on this will always be the same, regardless of the roll, as the roll rotates exactly around this line.

**Comment by adakite** [comment]
Got it!  Thank you !
