### ISSUE TITLE
Sign change of x in getRay()

### ISSUE THREAD

**Issue by nikcleju** [rgerum/cameratransform#15]
In RectilinearProjection function getRay(), there is a sign change for the X coordinate which doesn't appear in the doumentation:

```
        ray = np.array([-(points[..., 0] - self.center_x_px) / self.focallength_x_px,
                        (points[..., 1] - self.center_y_px) / self.focallength_y_px,
                        np.ones(points[..., 1].shape)]).T
```

Why the minus sign in front of  `-(points[..., 0] - self.center_x_px)` ? The functions docstring says no minus:
```
    .. math::
        \vec{r} = \begin{pmatrix}
            (x_\mathrm{im} - c_x)/f_x\\
            (y_\mathrm{im} - c_y)/f_y\\
            1\\
        \end{pmatrix}
```

I think this makes the `heading` angle be defined as positive CW, instead of CCW as shown in the 3D representations of the Coordinate Systems on readthedocs. However, I'm wondering if this is the only impact or it may have some other unintended consequences down the road.

**Comment by rgerum** [comment]
Thanks for the detailed look at the equations. It seems that I forgot the sign at all three projections for the x direction. The heading direction in the docs was a separate issue that I also fixed.

The definition as it was in the code was the right one, as I in the tests, I propagate rays from the pixel to the space and back and check if the calculations are self consistent.
