### ISSUE TITLE
imageFromGPS doesn't return correct pixel location

### ISSUE THREAD

**Issue by justinschlottman** [rgerum/cameratransform#17]
imageFromGPS doesn't return correct pixel locations for my nadir pointing camera. I get nan's. If I come slightly off nadir, like 10 degrees, I get pixel locations way outside the image size. Even going up to 45 degrees tilt, I'm getting incorrect pixel locations. 

Here's some example code of the problem:
import cameratransform as ct

imageWidth = 2048
imageHeight = 1536
pixelSizeMm = 0.00345

focalLengthMm = 8
sensorSizeMm = (imageWidth*pixelSizeMm,
                imageHeight*pixelSizeMm)

cam = ct.Camera(ct.RectilinearProjection(focallength_mm=focalLengthMm,
                                         sensor=sensorSizeMm,
                                         image=(imageWidth, imageHeight)),
                ct.SpatialOrientation(elevation_m=20,
                                      tilt_deg=0,
                                      roll_deg=0,
                                      heading_deg=0
                                      ))

lat = 33.8121 
lon = -117.9190
el = 0
cam.setGPSpos(lat, lon, el)

centerPixel = [imageWidth/2,  imageHeight/2, el]
centerGps = cam.gpsFromImage(centerPixel)
centerPixelFromGps = cam.imageFromGPS(centerGps)

print(f'Pixel: {centerPixel}')
print(f'Expected GPS: {lat} {lon} {el}')
print(f'Center GPS: {centerGps}')
print(f'Center Pixel: {centerPixelFromGps}')

And I get the following results for
0 tilt:
Pixel: [1024.0, 768.0, 0]
Expected GPS: 33.8121 -117.919 0
Center GPS: [  33.8121 -117.919     0.    ]
Center Pixel: [nan nan]

10 tilt:
Pixel: [1024.0, 768.0, 0]
Expected GPS: 33.8121 -117.919 0
Center GPS: [  33.8121 -117.919     0.    ]
Center Pixel: [  1024.        -12382.7984223]

45 tilt:
Pixel: [1024.0, 768.0, 0]
Expected GPS: 33.8121 -117.919 0
Center GPS: [  33.8121 -117.919     0.    ]
Center Pixel: [ 1024.         -1550.84057971]

80 tilt:
Pixel: [1024.0, 768.0, 0]
Expected GPS: 33.8121 -117.919 0
Center GPS: [  33.8121 -117.919     0.    ]
Center Pixel: [1024.          359.12584184]

**Comment by Kiwa21** [comment]
Hello, 
I get the same results with other cam parameter.

center_pixel=[640,360]
center_gps = gpsFromImage(center_pixel)       seems OK
center_cam = cam.imageFromGPS(center_gps)    is wrong, it gives [640,231.95476472]

@rgerum any ideas?

**Comment by rgerum** [comment]
Two things here, using cam.setGPSpos(lat, lon, el) with an elevation will overwrite the elevation already provided by the SpatialOrientation setup as they share for consistency the same parameter. So just call setGPSpos without the elevation parameter.
Second there was a bug in the code where the elevation messed with the gps -> space (and therefore also gps -> space -> image transformation), I fixed that bug.
if you update with

    pip install git+https://github.com/rgerum/cameratransform --upgrade

it should work now.

**Comment by Kiwa21** [comment]
Just for reference, I made it work by defining the function 


def imgFromGPS(point1):
    distance_pt =  ct.getDistance((lat, lon, relative_altitude),point1)
    bearing_rad_pt = np.deg2rad(ct.getBearing((lat, lon, relative_altitude),point1))
    x_d_pt =  distance_pt * np.sin(np.deg2rad(tilt_deg)) * np.sin(bearing_rad_pt)
    y_d_pt = distance_pt * np.sin(np.deg2rad(tilt_deg)) * np.cos(bearing_rad_pt)
    z_d_pt = 0
    gps_pt = cam.imageFromSpace([x_d_pt,y_d_pt,z_d_pt])
    return gps_pt
    
    
    Not sure it works all the time though !
    I'll try your fix now :)

**Comment by Kiwa21** [comment]
I didn't do the math for my code, I was just searching quickly to get the good center pixel from the GPS pos. i'm realising now than I'm probably missing the roll angle since in my case it was 0.
But from comparing this codewith yours, it seems to be a projection issue ?

**Comment by rgerum** [comment]
Well my code basically first goes from image to space and then it just goes from this space by using distance from camerapos and bearing in "space" and transfers them to the GPS.

**Comment by Kiwa21** [comment]
Your fix seems to work :)
pip install git+https://github.com/rgerum/cameratransform --upgrade    alone didn't work yesterday, I pip uninstall cameratransform first then reinstall it with pip install git+https://github.com/rgerum/cameratransform --upgrade

Thanks a lot for your amazing job !
