### ISSUE TITLE
Geolocalization of Drone Image

### ISSUE THREAD

**Issue by ricky1192** [rgerum/cameratransform#18]
Thank you so much for your wonderful library first.
Despite various tests, I find myself having problems in the geolocation of an image taken through the use of a drone.
Using the following code I have problems with image rotation and I was wondering if by chance I was misusing the tilt_deg, roll_deg and heading_deg parameters within SpatialOrientation.
Do you by any chance know where I'm wrong?
Thank you in advance

```

import cameratransform as ct

metadata = {
    "ImageWidth": 640,
    "ImageHeight": 512,
    "FocalLength": "19.0 mm",
    "RelativeAltitude": 87.599998,
    "GimbalRollDegree": 0,
    "GimbalYawDegree": 0.6,
    "GimbalPitchDegree": -90,
    "FlightRollDegree": -0.6,
    "FlightYawDegree": 89.300003,
    "FlightPitchDegree": 0.4,
    "GPS GPSLatitude": -17.25213463888889,
    "GPS GPSLongitude": -71.18490022222223,
}

image_size = (metadata["ImageWidth"], metadata["ImageHeight"])
sensor_width_mm = 7.44
sensor_height_mm = 5.55
sensor_size = (sensor_width_mm, sensor_height_mm)
focal_length = float(metadata["FocalLength"][:-3])
tilt_deg = metadata["FlightPitchDegree"]
roll_deg = metadata["FlightRollDegree"]
heading_deg = metadata["FlightYawDegree"]
relative_altitude = metadata["RelativeAltitude"]
lat = metadata["GPS GPSLatitude"]
lon = metadata["GPS GPSLongitude"]
cam = ct.Camera(
    ct.RectilinearProjection(focallength_mm=focal_length, sensor=sensor_size, image=image_size),
    ct.SpatialOrientation(
        elevation_m=relative_altitude,
        tilt_deg=tilt_deg,
        roll_deg=roll_deg,
        heading_deg=heading_deg,
    ),
)
cam.setGPSpos(lat, lon, relative_altitude)

center_pixel = [image_size[0]/2, image_size[1]/2, relative_altitude]
cam.gpsFromImage(center_pixel)

```

**Comment by rgerum** [comment]
I think your angles are defined differently. Pitch for an aircraft is 0 when heading parallel to the ground (e.g. looking forward). CameraTransform defines tilt as 0 when the camera faces down. So you should probably use 90-metadata["FlightPitchDegree"].
Then your points should already be roughly in the right place. Maybe you still need to change the sign of the heading and/or roll. But as they are quite small in your case it only should make a small difference.
You can use the documentation to get a feeling of how the angles are defined thought this interactive widget.
https://cameratransform.readthedocs.io/en/latest/coordinate_systems.html
