### ISSUE TITLE
Question :

### ISSUE THREAD

**Issue by KOuldamer** [rgerum/cameratransform#19]
Hi, 
I am currently working on Deep single image calibration. I want to train a CNN to predict distortion parameters : focal, pitch, roll and distortion parameters : k1, k2 of the radial distortion model : xd=x*(1+k1r2+k2r4). Is there any code to generate traning images from panorama with random parameters (focal, pitch, roll, k1, k2)?

**Comment by rgerum** [comment]
Well you could basically transform an image that you know to another distortion. You can basically use two camera objects and project from one camera to the other.
