### ISSUE TITLE
Rectilinear Projection init args view_x_deg/view_y_deg seem not correctly set

### ISSUE THREAD

**Issue by dualpair** [rgerum/cameratransform#24]
The following assertions unexpectedly don't pass:

```python
projection = cameratransform.RectilinearProjection(
    view_x_deg=61.617,
    image=(4608, 3456)
)
assert abs(projection.getFieldOfView()[0] - 61.617) < 1e-5
```

```python
projection = cameratransform.RectilinearProjection(
    view_y_deg=48.192,
    image=(4608, 3456)
)
assert abs(projection.getFieldOfView()[1] - 48.192) < 1e-5
```

**Comment by rgerum** [comment]
I will have a look why this could be the case. Thanks for providing this minimal example.

**Comment by rgerum** [comment]
You were right the initialization with this parameter combination was not properly implemented. I fixed it now and added tests to ensure this case works. Thanks for the clear bug report.
