### ISSUE TITLE
Validate possible combinations of init args in CameraProjection

### ISSUE THREAD

**Issue by dualpair** [rgerum/cameratransform#25]
Thanks for quickly fixing the issue https://github.com/rgerum/cameratransform/issues/24.

Concerning the passing of redundant parameters I also observed the following:
```python
projection = cameratransform.RectilinearProjection(
    view_x_deg=61.617,
    view_y_deg=41.617,
    sensor_width_mm=12, #  or  sensor_height_mm=12
    image=(4608, 3456)
)
assert abs(projection.getFieldOfView()[0] - 61.617) < 1e-5 # passes
assert abs(projection.getFieldOfView()[1] - 41.617) < 1e-5 # fails here in both cases
```
that may be a disorienting asymmetry. Ideally, in this case I would expect a `ValueError` to be raised in order to protect against possible abuses of the API.

Without changing the current API, I think it could be already beneficial to refactor the logic that mixes-and-matches the parameters in the CameraProjection `__init__()` into individual helper methods that validate the input on a case-by-case basis.

**Comment by rgerum** [comment]
I now implemented more checks on the input parameters. I hope that I have now covered all the cases of combinations. Thanks for pointing that problem out.
