### ISSUE TITLE
patch for spatial.py

### ISSUE THREAD

**Issue by eungyu-1** [rgerum/cameratransform#36]
Thank you for great job.
I found bug in spatial.py, need to fix.

line 107~
    def _initCameraMatrix(self, height=None, tilt_angle=None, roll_angle=None):
        if self.heading_deg < -360 or self.heading_deg > 360:  # pragma: no cover
            self.heading_deg = self.heading_deg % 360
        # convert the angle to radians
        tilt = np.deg2rad(self.parameters.tilt_deg)
        roll = np.deg2rad(self.parameters.roll_deg)
        heading = np.deg2rad(self.parameters.heading_deg)

        # get the translation matrix and rotate it
        self.t = np.array([self.parameters.pos_x_m, self.parameters.pos_y_m, self.parameters.elevation_m])

        # construct the rotation matrices for tilt, roll and heading
        self.R_tilt = np.array([[1, 0, 0],
                                [0, np.cos(tilt), np.sin(tilt)],
                                [0, -np.sin(tilt), np.cos(tilt)]])
        self.R_roll = np.array([[np.cos(roll), 0, -np.sin(roll)],
                                [0, 1, 0],
                                [np.sin(roll), 0, np.cos(roll)]])
        self.R_head = np.array([[np.cos(heading), -np.sin(heading), 0],
                                [np.sin(heading), np.cos(heading), 0],
                                [0, 0, 1]])

        self.R = np.dot(np.dot(self.R_tilt, self.R_roll), self.R_head)
        self.R_inv = np.linalg.inv(self.R)

reference : https://en.wikipedia.org/wiki/Rotation_matrix

**Comment by rgerum** [comment]
The 3D rotation matrices should be fine and implement the coordinate system as described in the docs (https://cameratransform.readthedocs.io/en/latest/coordinate_systems.html). There are may ways in which to define a 3D system of rotation angles and the "best" one depends strongly on the context.
If there is some deviation of the implementation from the docs, feel free to file a bug report for that. But from your information I am not sure what part exactly you consider the bug.

**Comment by rgerum** [comment]
@eungyu-1 I will close the issue for now. Feel free to reopen it if you still think there is a bug.
