### ISSUE TITLE
no attribute deg2rad on getBearing

### ISSUE THREAD

**Issue by huntergregal** [rgerum/cameratransform#5]
* Python3 3.6.9

```
Traceback (most recent call last):
  File "./solve.py", line 45, in <module>
    tilt =  ct.getBearing((sat_lat,sat_lon), (statue[0], statue[1]))
  File "/usr/local/lib/python3.6/dist-packages/cameratransform/gps.py", line 315, in getBearing
    lat1, lon1, h1 = splitGPS(point1)
  File "/usr/local/lib/python3.6/dist-packages/cameratransform/gps.py", line 326, in splitGPS
    lat1 = np.deg2rad(x[..., 0])
AttributeError: 'Angle' object has no attribute 'deg2rad'
```

**Comment by rgerum** [comment]
It seems that np is not numpy in this case but an "Angle" object? Could yo provide a minimal example that reproduces this bug?

**Comment by huntergregal** [comment]
If I'm being honest - I dont remember haha.

This was for HackASat quals (CTF) - but i cannot recall the challenge or scenario. (we won finals though!)

You may just close this issue if you wish.

**Comment by rgerum** [comment]
Then congratulations for winning the finals :-) Glad to hear that CameraTransform could help you with your task.
I'll close this issue now.
